### ISSUE TITLE
com.goyeau::mill-scalafix:8cfaccf  not found

### ISSUE THREAD

**Issue by ranglang** [joan38/mill-scalafix#1]
```com.goyeau::mill-scalafix:8cfaccf ``` not working

did you publish to maven repository

**Comment by joan38** [comment]
Let me release `0.1.0`

**Comment by joan38** [comment]
Meanwhile you can use import `$ivy.`com.goyeau::mill-scalafix:8515ae6``

**Comment by joan38** [comment]
`0.1.0` released.

Thanks
