### ISSUE TITLE
SemanticDB is always enabled. Also when publishing libraries.

### ISSUE THREAD

**Issue by lolgab** [joan38/mill-scalafix#101]
When publishing a library using mill-scalafix, the final artifacts end up having semanticdb files in them.

**Comment by lefou** [comment]
mill-scalafix should probably take advantage of the recently added semanticDB support in Mill. All `ScalaModule`s provide a `semanticDbData` target.

**Comment by lolgab** [comment]
@joan38 Can you tag a release with this fix?
