### ISSUE TITLE
Possiblity to have `scalafixScalaBinaryVersion`?

### ISSUE THREAD

**Issue by ckipp01** [joan38/mill-scalafix#11]
I believe this is actually related to #7, but I just came across this when trying to use `ExplicitResultTypes` on a project in 2.13.3. Currently you get an error like this:

```
[E0] The ExplicitResultTypes rule needs to run with the same Scala binary version as the one used to compile target sources (2.13). To fix this problem, either remove ExplicitResultTypes from .scalafix.conf or make sure the scalafixScalaBinaryVersion setting key matches 2.13.
```

The error is pretty specific to sbt, since it references a setting key, but would it be possible to add something like this so if someone hits on this they are able to just provide the scalafixScalaBinaryVersion in this scenario?

Also, super glad to see a scalafix mill integration 👍

**Comment by joan38** [comment]
Could you try with the version `a7cb931` and let me know if it fixes your issue?

**Comment by ckipp01** [comment]
Hi @joan38, I just gave it a try with the latest commit and I still get the same error.

**Comment by joan38** [comment]
Thanks @ckipp01 that actually make sense. Could you review #13?

cc @DamianReeves

**Comment by ckipp01** [comment]
Just tried it out. Works great! 👍
