### ISSUE TITLE
diff and diff-base not working as expected

### ISSUE THREAD

**Issue by IdiosApps** [joan38/mill-scalafix#119]
I was hoping to use some scalafix options to skip fixing of unchanged files compared to a `main` branch (to speedup CI).

I am not seeing a speedup, or even a difference in logging, when using the [`--diff-base` option](https://scalacenter.github.io/scalafix/docs/users/installation.html#help).

The following snippets are run inside this repo, on latest `main`. 

--check works as expected _(actually... I'm not so sure! Technically --check "Won't write to files." - which contradicts the output here!)._
```
./mill all "__.fix --check"
[1/1] all > [47/47] mill-scalafix[0.10.7].fix
Rewriting and linting 3 Scala sources against 4 rules
```

with --check, --diff-base doesn't have impact:
```
❯ ./mill all "__.fix --check --diff-base main"
[1/1] all > [47/47] mill-scalafix[0.10.7].fix 
Rewriting and linting 3 Scala sources against 4 rules
```

even just --diff-base on its own seems to have no impact:
```
❯ ./mill all "__.fix --diff-base main"
[1/1] all > [47/47] mill-scalafix[0.10.7].fix 
Rewriting and linting 3 Scala sources against 4 rules
```

When running this on main (or a branch off main, with no some or no changes), it gives the same output.

The output I am expecting: No log line, when `--diff-base main` is used.

Similarly, using `--files /absolute/path/to/ScalafixModule.scala` still results logs about checking 3 Scala sources. I didn't successfully validate if more than 1 file is changed. I tried, by breaking a few rules in e.g. ScalafixModule, but they failed even with the rules commented out in .scalafix.conf.

---

It looks like running `sbt "scalafixAll --check"` (stolen from scalafix'sGitHub Action CI script) and `sbt "scalafixAll --check --diff-base main"` in the scalafix repo give similar results with no obserable speedup, so I can open a ticket there and link to this one.

---

A fix could be to parse (some of) the args and use that in the filesToFix method, but it's probably better done in scalafix. I didn't think too closely about it yet.

I think some arg parsing of e.g. `--check` would be necessary to give more accurate logs - e.g. `[CHECK] Would rewrite and lint 3 Scala sources against 4 rules`

**Comment by lefou** [comment]
I think you are mixing sbt and Mill cli syntax here. In Mill, you should not put the target and its parameters into the same quote. Also, the `all` command is deprecated and is not necessary in this situation. (In case you want to run another target just use a standalone `+`.)

Your first mill cli should look like this:

```
./mill __.fix --check
```

In case you need to quote for some reasons, the second command could look like this:

```
./mill "__.fix" "--check" "--diff-base" "main"
```

and so on.

**Comment by IdiosApps** [comment]
I see about `all` 🙇‍♂️, I was grabbing from https://github.com/joan38/mill-scalafix/blob/main/.github/workflows/ci.yml#L23

I also tried like `./mill __.fix --check --diff-base main`.
`./mill __.fix --check --diff-base` gives an error asking for a value for `diff-base`, so I thought the above command is OK. If not using any quotes, is it correct?

---

Over a few runs, first 2 on `main`, 2 on a branch off of main:
`time mill -j 0 __.fix --check --diff-base main` takes 2m25s, 1m9s, 1m8s, 1m8s

`time mill -j 0 __.fix --check` takes 44s, 40s, 42s, 38s

It looks like `--diff-base main` on the private codebase I'm in is having a noticable negative impact!

I was hoping that scalafix would be like scalafmt for caching/diffing: for the private repo I'm working on, re-using compilation output takes scalafmt (via mill) from a couple minutes down to 1 second. If a few files changed, compared to the `out` cache, it might be like 10 seconds - still a huge improvement when 90%+ of files don't change.

**Comment by joan38** [comment]
Sounds like I can close this one since this is filled with scalacenter/scalafix directly?
