### ISSUE TITLE
Update version of semanticdb used, and allow specification of semanticdb-scalac version

### ISSUE THREAD

**Issue by DamianReeves** [joan38/mill-scalafix#7]
Now with scala 2.13.3 being out I am having some issues with my build around the semanticdb versions. Is it possible to both update the handling for scala 2.13.3 and allow for separate configuration of the semanticdb-scalac version.

**Comment by joan38** [comment]
I've upgraded the semanticdb-scalac version. `0.1.4` should be published in a moment by CI.
With the current logic you can override `scalacPluginIvyDeps` and set the `semanticdb-scalac` you want.

**Comment by DamianReeves** [comment]
Thanks for this. 
It looks like the build failed.

**Comment by DamianReeves** [comment]
By the way, the thing about overriding the `scalacPluginIbyDeps` entirely is that you then have to filter out the `semanticdb-scalac` version manually and then re-add. Since I wasn't getting code completion, see how to filter involved digging through code to see what the `Deps` type from `mill` looks like and how the `Dependency` and `Module` types from `coursier` looked as well.

It was a few hops.

Thats why I was suggesting a separate target like: `scalafixCompilerPluginIvyDeps` which can then be applied to the `scalacPluginIvyDeps` like:

```scala
def scalafixCompilerPluginIvyDeps = T {
    Agg(ivy"org.scalameta:::semanticdb-scalac:4.3.18")
}

override def scalacPluginIvyDeps: Target[Loose.Agg[Dep]] =
    super.scalacPluginIvyDeps() ++ scalafixCompilerPluginIvyDeps()
```

I think this makes things a little easier to configure from the user standpoint.

**Comment by joan38** [comment]
This is now published.

I agree the current implementation is not easy but that should not be a problem if the plugin is upgraded in time.
I'm wondering why Scala Stewart didn't pick this up.

**Comment by DamianReeves** [comment]
Thanks for publishing
