### ISSUE TITLE
Version 0.2.7 is not published to Maven

### ISSUE THREAD

**Issue by jiegec** [joan38/mill-scalafix#86]
Error message:

```
Failed to resolve ivy dependencies:Error downloading com.goyeau:mill-scalafix_2.13:0.2.7
  not found: ~/.ivy2/local/com.goyeau/mill-scalafix_2.13/0.2.7/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/goyeau/mill-scalafix_2.13/0.2.7/mill-scalafix_2.13-0.2.7.pom
```

**Comment by joan38** [comment]
Sonce 0.2.7 it's suffixed with `_mill0.9` or `_mill0.10`:
`com.goyeau:mill-scalafix_mill0.9_2.13:0.2.7`

**Comment by ricochet1k** [comment]
It took me a long time to find this, please update your README to mention this

**Comment by joan38** [comment]
The readme is up to date:
```
import $ivy.`com.goyeau::mill-scalafix::<latest version>
```
Mind the double colon `::` between the artifact and version too that will add the right `_mill` version
